package(
    default_visibility = ["//visibility:public"],
)

load(":toolchain.bzl", "declare_toolchains")

exports_files(["toolchain.bzl"])

toolchain_type(name = "toolchain_type")

declare_toolchains()
